# Problem 1

## Introduction

### Say "Hello, World!" With Python

In [1]:
print("Hello, World!")

Hello, World!


### Python If-Else

In [2]:
#!/bin/python3

import math
import os
import random
import re
import sys

def _analysis(n):
    if (n % 2 != 0):
        return "Weird"
    if(n>=2 and n<=5 ):
        return "Not Weird"
    if(n>=6 and n<=20):
        return "Weird"
    if(n>=20):
        return "Not Weird"        
    

if __name__ == '__main__':
    n = int(input().strip())
    if (n>=1 and n<=100):
        print(_analysis(n))

 2


Not Weird


### Arithmetic Operators

In [3]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

 3
 10


13
-7
30


### Python: Division

In [4]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

 6
 3


2
2.0


### Loops

In [5]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)

 3


0
1
4


### Write a function

In [6]:
def is_leap(year):
    leap = False
    if(year%4 == 0):
        leap=True
    if(year%100==0):
        leap=False
    if(year%400==0):
        leap=True
    return leap

### Print Function

In [7]:
if __name__ == '__main__':
    n = int(input())
    numbers=[]
    for i in range(n):
        print(i+1,end='')

 5


12345

## Basic Data Types

### List Comprehensions

In [20]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    print([[i, j, k] 
    for i in range(x + 1) for j in range(y + 1) for k in range(z + 1) if i + j + k != n])

 1
 1
 1
 2


[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


### Find the Runner-Up Score!

In [22]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    my_list = list(set(arr))
    my_list.sort()
    if len(my_list) == 1:
        print(my_list[0])
    elif len(my_list) >= 2:
        print(my_list[-2])

 5
 2 3 6 6 5


5


### Nested Lists

In [23]:
def second_lowests(grades):
    grades = iter(grades)
    lname, lowest = next(grades)
    slname, slowest = next(grades)
    if slowest < lowest:
        lowest, slowest = slowest, lowest
        names = [lname]
    elif slowest == lowest: # we don't know, if lowest can be second lowest!
        names = [lname, slname]
    else:
        names = [slname]

    for name, score in grades:
        if score == slowest:
            names.append(name)
            continue
        if score == lowest:
            continue
        if score < lowest:
            if slowest == lowest:
                pass
            else:
                names = [lname]
            lowest, slowest = score, lowest
            lname = name
        elif score < slowest:
            slowest = score
            names = [name]
        elif score > slowest and slowest == lowest:
            slowest = score
            names = [name]

    if slowest == lowest: # all have same score
        return []
    names.sort()
    return names


if __name__ == '__main__':
    lista = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        lista.append([name, score])
    assert 2 <= len(lista) <= 5
    print ("\n".join(second_lowests(lista)))

 5
 Harry
 37.21
 Berry
 37.21
 Tina
 37.2
 Akriti
 41
 Harsh
 39


Berry
Harry


### Finding the percentage

In [24]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    print("%.2f" %(sum(student_marks[query_name])/len(student_marks[query_name])))

 3
 Krishna 67 68 69
 Arjun 70 98 63
 Malika 52 56 60
 Malika


56.00


### Lists 

In [19]:
n = input()
print(n)
l = []
for _ in range(int(n)):
    s = input().split()
    cmd = s[0]
    args = s[1:]
    if cmd !="print":
        cmd += "("+ ",".join(args) +")"
        eval("l."+cmd)
    else:
        print (l)

 12


12


 insert 0 5
 insert 1 10
 insert 0 6
 print


[6, 5, 10]


 remove 6
 append 9
 append 1
 sort
 print


[1, 5, 9, 10]


 pop
 reverse
 print


[9, 5, 1]


### Tuples

In [25]:
if __name__ == '__main__':
    n = int(input())
    integer_list = list(map(int, input().split()))
    t = tuple(integer_list)
    print(hash(t))

 2
 1 2


-3550055125485641917


## Strings

### sWAP cASE

In [27]:
def swap_case(s):
    return s.swapcase()

### String Split and Join



In [28]:
def split_and_join(line):
    T = line.split(" ")
    return ("-".join(T))

### What's Your Name?



In [29]:
def print_full_name(a, b):
    print ("Hello", a, b + "! You just delved into python.")

### Mutations

In [30]:
def mutate_string(string, position, character):
    pos = position+1
    Output = string[:position]+character+string[pos:]
    return Output

### Find a string



In [31]:
def count_substring(string, sub_string):
    count = start = 0
    while True:
        start = string.find(sub_string, start) + 1
        if start > 0:
            count+=1
        else:
            return count

### String Validators



In [32]:
if __name__ == '__main__':
    s = input()
    print (any(c.isalnum() for c in s))
    print (any(c.isalpha() for c in s))
    print (any(c.isdigit() for c in s))
    print (any(c.islower() for c in s))
    print (any(c.isupper() for c in s))

 qA2


True
True
True
True
True


### Text Alignment



In [33]:
thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

 5


    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


### Text Wrap



In [34]:
def wrap(string, max_width):
    return (textwrap.fill(string, max_width))

### Designer Door Mat



In [35]:
if __name__ == "__main__":
    N, M = map(int, input().split())

    stick = '.|.'

    for i in range(1, N, 2): 
        sticks = stick * i
        print(sticks.center(M, '-'))

    print('WELCOME'.center(M, '-'))

    for i in range(N - 2, -1, -2): 
        sticks = stick * i
        print(sticks.center(M, '-'))

 7 21


---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


### String Formatting



In [36]:
def print_formatted(number):
    width = len("{0:b}".format(number))

    for i in range(1, number + 1):
        print("{0:{w}d} {0:{w}o} {0:{w}X} {0:{w}b}".format(i, w = width))

### Alphabet Rangoli



In [37]:
def print_rangoli(size):
    width  = size*4-3
    string = ''

    for i in range(1,size+1):
        for j in range(0,i):
            string += chr(96+size-j)
            if len(string) < width :
                string += '-'
        for k in range(i-1,0,-1):    
            string += chr(97+size-k)
            if len(string) < width :
                string += '-'
        print(string.center(width,'-'))
        string = ''

    for i in range(size-1,0,-1):
        string = ''
        for j in range(0,i):
            string += chr(96+size-j)
            if len(string) < width :
                string += '-'
        for k in range(i-1,0,-1):
            string += chr(97+size-k)
            if len(string) < width :
                string += '-'
        print(string.center(width,'-'))

### Capitalize!



In [39]:
def solve(s):
    for i in s.split():
        s = s.replace(i,i.capitalize())
    return s

### The Minion Game



In [40]:
def minion_game(string):
    vowels = {'A','E','I','O','U'}
    kevin = 0
    stuart = 0
    for i in range(len(string)):
        if string[i] in vowels:
            kevin += len(string) - i
        else:
            stuart += len(string) - i

    if kevin == stuart:
        print("Draw")
    elif kevin > stuart:
        print("Kevin " + str(kevin))
    else:
        print("Stuart " + str(stuart))

### Merge the Tools!



In [41]:
def merge_the_tools(string, k):
    for i in range(0,len(string), k):
        line = string[i:i+k]
        new = ""
        for i in line:
            if i not in new:
                new+=i
        print(new)

## Sets

### Introduction to Sets



In [1]:
def average(array):
    b = set(array)
    return sum(b)/len(b)

## No Idea!



In [2]:
if __name__ == "__main__":
    n_m = input().split()
    n_m = map(int, n_m)
    n = map(int, input().split())
    A = set(map(int, input().split()))
    B = set(map(int, input().split()))

    counter = 0
    for i in n:
        if i in A:
            counter += 1
        elif i in B:
            counter -= 1

    print (counter)

 3 2
 1 5 3
 3 1
 5 7


1


### Symmetric Difference



In [3]:
if __name__ =="__main__":
    int(input())
    N = input().split()
    Nint = set(list(map(int, N)))
    int(input())
    M = input().split()
    Mint = set(list(map(int, M)))
    res = []
    for i in list(Nint.difference(Mint)):
        res.append(i)
    for j in list(Mint.difference(Nint)):
        res.append(j)
    for k in sorted(res):
        print (k)

 4
 2 4 5 9
 4
 2 4 11 12


5
9
11
12


### Set .add()



In [4]:
if __name__ == "__main__":
    N = int(input())
    s = set(input() for i in range(N))
    print (len(s))

 7
 UK
 China
 USA
 France
 New Zealand
 UK
 France


5


### Set .discard(), .remove() & .pop()



In [5]:
if __name__ == "__main__":
    n = int(input())
    s = set(map(int,input().split()))
    num = int(input())
    for i in range(num):
        ip = input().split()
        if ip[0]=="remove":
            s.remove(int(ip[1]))
        elif ip[0]=="discard":
            s.discard(int(ip[1]))
        else :
            s.pop()
    print(sum(list(s)))

 9
 1 2 3 4 5 6 7 8 9
 10
 pop
 remove 9
 discard 9
 discard 8
 remove 7
 pop
 discard 6
 remove 5
 pop
 discard 5


4


### Set .union() Operation



In [6]:
if __name__ == "__main__":
    e = input()
    el = set(map(int,input().split()))
    f = input()
    fl = set(map(int,input().split()))
    u = el.union(fl)
    print (len(u))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


13


### Set .intersection() Operation



In [7]:
if __name__ == "__main__":
    eng_num = int(input())
    eng_set = input().split()
    eng_set = set(map(int, eng_set))
    fren_num = int(input())
    fren_set = input().split()
    fren_set = set(map(int, fren_set))

    print (len(eng_set.intersection(fren_set)))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


5


### Set .difference() Operation



In [8]:
if __name__ =="__main__":
    eng_num = int(input())
    eng_set = set(map(int, input().split()))
    fren_num = int(input())
    fren_set = set(map(int, input().split()))

    print (len(eng_set.difference(fren_set)))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


4


### Set .symmetric_difference() Operation



In [9]:
if __name__ == "__main__":
    a = int(input())
    b = input().split()
    b = list(map(int, b))
    c = int(input())
    d = input().split()
    d = list(map(int, d))

    print (len(set(b).symmetric_difference(set(d))))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


8


### Set Mutations



In [10]:
if __name__ == "__main__":
    a = int(input())
    A = set(map(int, input().split()))
    for i in range(int(input())):
        s, b = input().split()
        if s == 'intersection_update':
            A &= set(map(int, input().split()))
        elif s == 'update':
            A |= set(map(int, input().split()))
        elif s == 'symmetric_difference_update':
            A ^= set(map(int, input().split()))
        else:
            A -= set(map(int, input().split()))
    print (sum(A) )

 16
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
 4
 intersection_update 10
 2 3 5 6 8 9 1 4 7 11
 update 2
 55 66
 symmetric_difference_update 5
 22 7 35 62 58
 difference_update 7
 11 22 35 55 58 62 66


38


### The Captain's Room



In [11]:
from collections import Counter

if __name__ == "__main__":
    n = input()
    b = input().split()

    k = Counter(b)

    d = dict(k)

    print (min(d, key=lambda k: d[k]))

 5
 1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2


8


### Check Subset



In [12]:
if __name__ == "__main__":
    for i in range(int(input())): 
        a = int(input())
        A = set(input().split()) 
        b = int(input())
        B = set(input().split())
        print(A <= B)

 3
 5
 1 2 3 5 6
 9
 9 8 5 6 3 2 1 4 7


True


 1
 2
 5
 3 6 5 4 1


False


 7
 1 2 3 5 6 8 9
 3
 9 8 2


False


### Check Strict Superset



In [13]:
if __name__ == "__main__":
    storage = set(input().split())
    N = int(input())
    output = True

    for i in range(N):
        storage2 = set(input().split())
        if not storage2.issubset(storage):
            output = False
        if len(storage2) >= len(storage):
            output = False

    print(output)

 1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
 2
 1 2 3 4 5
 100 11 12


False


## Collections

### collections.Counter()



In [14]:
if __name__ == "__main__":
    from collections import Counter
    X = int(input())
    N = map(int,input().split())
    x = int(input())
    L = map(tuple,(map(int,input().split()) for _ in range(x)))
    n = Counter(N)
    p =0
    for i in L:
        if i[0] in n.keys() and n[i[0]] >0 :
            n[i[0]] = n[i[0]]-1
            p = p+i[1]
          
    print(p)

 10
 2 3 4 5 6 8 7 6 5 18
 6
 6 55
 6 45
 6 55
 4 40
 18 60
 10 50


200


## DefaultDict Tutorial



In [15]:
from collections import defaultdict


if __name__ == "__main__":
    d = defaultdict(list)
    n, m = map(int, input().split())

    for i in range(n):
        d[input()].append(str(i + 1))
    for j in range(m):
        print(' '.join(d[input()]) or -1)

 5 2
 a
 a
 b
 a
 b
 a


1 2 4


 b


3 5


## Collections.namedtuple()



In [16]:
from collections import namedtuple

if __name__ == "__main__":
    n = int(input())
    fields = input().split()

    total_marks = 0
    for _ in range(n):
        students = namedtuple('student', fields)
        MARKS, CLASS, NAME, ID = input().split()
        student = students(MARKS, CLASS, NAME, ID)
        total_marks += int(student.MARKS)
    print('{:.2f}'.format(total_marks / n))

 5
 ID         MARKS      NAME       CLASS
 1          97         Raymond    7
 2          50         Steven     4
 3          91         Adrian     9
 4          72         Stewart    5
 5          80         Peter      6


78.00


### Collections.OrderedDict()



In [17]:
from collections import *

if __name__ == "__main__":
    N = int(input());
    d = OrderedDict();
    for i in range(N):
        item = input().split()
        itemPrice = int(item[-1])
        itemName = " ".join(item[:-1])
        if(d.get(itemName)):
            d[itemName] += itemPrice
        else:
            d[itemName] = itemPrice
    for i in d.keys():
        print(i, d[i])

 9
 BANANA FRIES 12
 POTATO CHIPS 30
 APPLE JUICE 10
 CANDY 5
 APPLE JUICE 10
 CANDY 5
 CANDY 5
 CANDY 5
 POTATO CHIPS 30


BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


### Word Order



In [18]:
import collections;

if __name__ == "__main__":
    N = int(input())
    d = collections.OrderedDict()

    for i in range(N):
        word = input()
        if word in d:
            d[word] +=1
        else:
            d[word] = 1

    print(len(d));

    for k,v in d.items():
        print(v,end = " ")

 4
 bcdef
 abcdefg
 bcde
 bcdef


3
2 1 1 

### Collections.deque()



In [19]:
from collections import deque

if __name__ == "__main__":
    d = deque()
    actions = {
        "append":d.append, 
        "appendleft": d.appendleft,
        "pop": d.pop,
        "popleft": d.popleft
    }
    for i in range(int(input())):
        action = input().split()
        if len(action)>1:
            x,y = action
            actions[x](int(y))
        else:
            actions[action[0]]()
    print(*d)

 6
 append 1
 append 2
 append 3
 appendleft 4
 pop
 popleft


1 2


### Company Logo



In [20]:
#!/bin/python3

import math
import os
import random
import re
import sys
import collections



if __name__ == '__main__':
    s = sorted(input().strip())
    s_counter = collections.Counter(s).most_common()
    s_counter = sorted(s_counter, key=lambda x: (x[1] * -1, x[0]))
    for i in range(0, 3):
        print(s_counter[i][0], s_counter[i][1])

 aabbbccde


b 3
a 2
c 2


### Piling Up!



In [21]:
from collections import deque

if __name__ == "__main__":
    N = int(input())

    for _ in range(N):
        flag = True
        input()
        d = deque(map(int, input().strip().split()))
        if(d[0] >= d[-1]):
            max = d.popleft()
        else:
            max = d.pop()
        while d:
            if(len(d)==1):
                if(d[0] <= max):
                    break
                else:
                    flag = False
                    break
            else:
                if(d[0]<=max and d[-1]<=max):
                    if(d[0]>=d[-1]):
                        max = d.popleft()
                    else:
                        max = d.pop()
                elif(d[0]<=max):
                    max = d.popleft()
                elif(d[-1]<=max):
                    max = d.pop()
                else:
                    flag = False
                    break
        if flag:
            print("Yes")
        else:
            print("No")

 2
 6
 4 3 2 1 3 4


Yes


 3
 1 3 2


No


## Date and Time

### Calendar Module



In [22]:
import datetime
import calendar

if __name__ == "__main__":
    m, d, y = map(int, input().split())
    input_date = datetime.date(y, m, d)
    print(calendar.day_name[input_date.weekday()].upper())

 08 05 2015


WEDNESDAY


### Time Delta



In [ ]:
#!/bin/python3
# -*- coding: utf-8 -*-
import math
import os
import random
import re
import sys
from datetime import datetime

def time_delta(t1, t2):
    time_format = '%a %d %b %Y %H:%M:%S %z'
    t1 = datetime.strptime(t1, time_format)
    t2 = datetime.strptime(t2, time_format)
    return str(int(abs((t1-t2).total_seconds())))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')
    
    fptr.close()

## Exceptions

In [9]:
if __name__ ==  "__main__":
    for i in range(int(input())):
        try:
            a,b = list(map(int, input().split()))
            print(a//b)
        except ZeroDivisionError as e:
            print('Error Code:',e)
        except ValueError as e:
            print('Error Code:',e)

 3
 1 0


Error Code: integer division or modulo by zero


 2 $


Error Code: invalid literal for int() with base 10: '$'


 3 1


3


## Built-ins

### Zipped!

In [10]:
if __name__ == "__main__":
    N, X = input().split()
    out = list()
    for i in range(int(X)):
        ip = map(float, input().split())
        out.append(ip)
    for i in zip(*out): 
        print(sum(i)/len(i)) 

 5 3
 89 90 78 93 80
 90 91 85 88 86
 91 92 83 89 90.5


90.0
91.0
82.0
90.0
85.5


## Map and Lambda Function





In [11]:
cube = lambda x:x**3
    
def fibonacci(n):
    if n<2:
        return range(n)
    init = [0,1]
    for i in range(0,n-2):
        add =init[i+1]+init[i]
        init.append(add)
    return(init)

## Regex and Parsing

### Detect Floating Point Number



In [12]:
from re import match, compile

pattern = compile('^[-+]?[0-9]*\.[0-9]+$')
for _ in range(int(input())):
    print(bool(pattern.match(input())))

 4
 4.0O0


False


 -1.00


True


 +4.54


True


 SomeRandomStuff


False


### Re.split()



In [14]:
regex_pattern = r"[.,]+"

### Group(), Groups() & Groupdict()



In [15]:
import re
m = re.search(r'([A-Za-z0-9])\1+',input())
if m:
    print (m.group(1))
else:
    print (-1)

 12345678910111213141516171820212223


1


### Re.findall() & Re.finditer()



In [16]:
import re
consonants = 'qwrtypsdfghjklzxcvbnm'
vowels = 'aeiou'
match = re.findall(r'(?<=['+consonants+'])(['+vowels+']{2,})(?=['+consonants+'])',input(),flags = re.I)
if match:
    for i in match:
        print (i)
else:
    print (-1)

 rabcdeefgyYhFjkIoomnpOeorteeeeet


ee
Ioo
Oeo
eeeee


### Re.start() & Re.end()



In [ ]:
#!/bin/python3
import re
from collections import OrderedDict
od = OrderedDict()
S = input().strip()
k = input().strip()
i = 0
l = list()
if re.search(k,S) == None:
    print (-1,-1)
else :
    while i<len(S):
        m = re.search(k,S[i:])
        if m == None:
            break;
        else:
            p = i+m.start()
            n = (p,p+len(k)-1)
            od[i] = n
        i = i+1

    for p,s in enumerate(od.values()):
        if od.values()[p] != od.values()[p-1]:
            print (s)

### Regex Substitution



In [4]:
import re

for i in range(int(input())):
    print(re.sub(r'(?<= )(&&|\|\|)(?= )', lambda x: 'and' if x.group() == '&&' else 'or', input()))

 11
 a = 1;


a = 1;


 b = input();


b = input();


 if a + b > 0 && a - b < 0:


if a + b > 0 and a - b < 0:


     start()


    start()


 elif a*b > 10 || a/b < 1:


elif a*b > 10 or a/b < 1:


     stop()


    stop()


 print set(list(a)) | set(list(b))


print set(list(a)) | set(list(b))


 #Note do not change &&& or ||| or & or |


#Note do not change &&& or ||| or & or |


 #Only change those '&&' which have space on both sides.


#Only change those '&&' which have space on both sides.


 #Only change those '|| which have space on both sides.


#Only change those '|| which have space on both sides.


### Validating Roman Numerals



In [1]:
regex_pattern = r"^(?=[MDCLXVI])M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"	# Do not delete 'r'.


### Validating phone numbers



In [ ]:
import re
k = input()
p = [input() for i in range(k)]
for no in p:
    if len(str(no)) == 10 and bool(re.match (r'[789][\d]{9}',no)):
        print ("YES")
    else :
        print ("NO")


### Validating and Parsing Email Addresses



In [5]:
import re

N = int(input())

for i in range(N):
    name, email = input().split()
    pattern="<[a-z][a-zA-Z0-9\-\.\_]+@[a-zA-Z]+\.[a-zA-Z]{1,3}>"
    if bool(re.match(pattern, email)):
        print(name,email)


 2
 DEXTER <dexter@hotmail.com>


DEXTER <dexter@hotmail.com>


 VIRUS <virus!@variable.:p>


### Hex Color Code



In [ ]:
import re

T = input()
in_css = False
for _ in xrange(T):
    s = raw_input()
    if '{' in s:
        in_css = True
    elif '}' in s:
        in_css = False
    elif in_css:
        for color in re.findall('#[0-9a-fA-F]{3,6}', s):
            print color


### HTML Parser - Part 1



In [ ]:
from HTMLParser import HTMLParser
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print ("Start :", tag)
        #print attrs
        for i in attrs:
            print ("-> %s > %s"%(i[0],i[1]))
    def handle_endtag(self, tag):
        print ("End   :", tag)
    def handle_startendtag(self, tag, attrs):
        print ("Empty :", tag)
        for i in attrs:
            print ("-> %s > %s"%(i[0],i[1]))

data = [ raw_input() for _ in xrange(input())]
moddata = ''.join(data)

parser = MyHTMLParser()
parser.feed(moddata)

### HTML Parser - Part 2



In [ ]:
from HTMLParser import HTMLParser
import re

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if re.findall(r'\n',data):
            print ">>> Multi-line Comment \n",data
        else:
            print ">>> Single-line Comment \n",data
            
    def handle_data(self, data):
        if len(data) >1:
            print ">>> Data\n",data  
  
  
html = ""       
for i in range(int(raw_input())):
    html += raw_input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()


### Detect HTML Tags, Attributes and Attribute Values



In [ ]:
from __future__ import print_function
import sys
if sys.version_info[0]>=3:
    raw_input=input
    from html.parser import HTMLParser
else:
    from HTMLParser import HTMLParser

from HTMLParser import HTMLParser
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        for e in attrs: print("-> "+e[0]+" > "+str(e[1]))
    def handle_endtag(self, tag):
        #print("End   : "+tag)
        pass
    def handle_startendtag(self, tag, attrs):
        print(tag)
        for e in attrs: print("-> "+e[0]+" > "+str(e[1]))

parser = MyHTMLParser()
for _ in range(int(raw_input())):
    parser.feed(raw_input())


### Validating UID



In [ ]:
import re
for i in range(int(raw_input())):
    N = raw_input().strip()
    if N.isalnum() and len(N) == 10:
        if bool(re.search(r'(.*[A-Z]){2,}',N)) and bool(re.search(r'(.*[0-9]){3,}',N)):
            if re.search(r'.*(.).*\1+.*',N):
                print 'Invalid'
            else:
                print 'Valid'    
        else:
            print 'Invalid'
    else:
        print 'Invalid'


### Validating Credit Card Numbers



In [ ]:
import re
for i in range(int(raw_input())):
    S = raw_input().strip()
    pre_match = re.search(r'^[456]\d{3}(-?)\d{4}\1\d{4}\1\d{4}$',S)
    if pre_match:
        processed_string = "".join(pre_match.group(0).split('-'))
        final_match = re.search(r'(\d)\1{3,}',processed_string)
        print 'Invalid' if final_match else 'Valid'
    else:
        print 'Invalid'


### Validating Postal Codes



In [12]:
regex_integer_in_range = r"^[1-9][\d]{5}$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(\d)(?=\d\1)"	# Do not delete 'r'.



### Matrix Script



In [11]:
#!/bin/python

import math
import os
import random
import re
import sys




first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

matrix = list(zip(*matrix))

sample = str()

for words in matrix:
    for char in words:
        sample += char
       
print(re.sub(r'(?<=\w)([^\w\d]+)(?=\w)', ' ', sample)) 


 7 3
 Tsi
 h%x
 i #
 sM 
 $a 
 #t%
 ir!


This is Matrix#  %!


## XML

### XML 1 - Find the Score



In [12]:


def get_attr_number(node):
    count = 0
    for tag in node:
        count = count + get_attr_number(tag)
    return count + len(node.attrib)



### XML2 - Find the Maximum Depth



In [13]:


maxdepth = 0
def depth(elem, level):
    global maxdepth
    level += 1
    if (maxdepth < level):
        maxdepth = level
    for child in elem:
        depth(child, level)


## Closures and Decorators

### Standardize Mobile Number Using Decorators



In [14]:
def wrapper(f):
    def fun(l):
        f(['+91 ' + c[-10:-5] + ' ' + c[-5:] for c in l])
    return fun



### Decorators 2 - Name Directory



In [15]:


def person_lister(f):
    def inner(people):
        return map(f, sorted(people, key=lambda x: int(x[2])))
    return inner



## Numpy

### Arrays

In [16]:


def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)
    arr2 = numpy.array(arr[::-1], dtype = float)
    return arr2



### Shape and Reshape



In [20]:
import numpy

lis = numpy.array(input().split(' '), int)
print (lis.reshape(3, 3))


 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Transpose and Flatten



In [ ]:
import numpy

m = map(int,raw_input().split())
k = [map(int,raw_input().split()) for _ in xrange(m[0])]
n = numpy.array(k)
print numpy.transpose(n)
print n.flatten()




### Concatenate

In [ ]:
import numpy

NMP = map(int, raw_input().split())
N = numpy.array([raw_input().split() for i in range(NMP[0])], int)
M = numpy.array([raw_input().split() for i in range(NMP[1])], int)

print numpy.concatenate((N, M), axis = 0)




### Zeros and Ones



In [ ]:
import numpy
def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = numpy.zeros(arr1, dtype = int)
    arr3 = numpy.ones(arr1, dtype = int)
    return arr2, arr3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)




### Eye and Identity



In [15]:
import numpy

numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)



 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Array Mathematics



In [ ]:
import numpy

k = map(int,raw_input().split())
a,b = [],[]
for i in xrange(k[0]):
    a.append(map(int,raw_input().split()))
for i in xrange(k[0]):
    b.append(map(int,raw_input().split()))
A,B = numpy.array(a),numpy.array(b)
print numpy.add(A,B)
print numpy.subtract(A,B)
print numpy.multiply(A,B)
print numpy.divide(A,B)
print numpy.mod(A,B)
print numpy.power(A,B)



### Floor, Ceil and Rint



In [22]:
import numpy
numpy.set_printoptions(sign=' ')
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)

    floor = numpy.floor(arr1)
    ceil = numpy.ceil(arr1)
    rint = numpy.rint(arr1)

    return floor, ceil, rint    
arr = input().strip().split(' ')
floor, ceil, rint = arrays(arr)
print(floor)
print(ceil)
print(rint)




 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### Sum and Prod



In [17]:
import numpy

N, M = map(int, input().split())

array = numpy.array([input().split() for i in range(N)], int)

print(numpy.prod(numpy.sum(array, axis = 0), axis = None))



 2 2
 1 2
 3 4


24


### Min and Max



In [18]:
import numpy

N, M = map(int, input().split())

A = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))



 4 2
 2 5
 3 7
 1 3
 4 0


3


### Dot and Cross



In [19]:
import numpy
N = int(input())
A = numpy.array([input().split() for i in range(N)], dtype =int)
B = numpy.array([input().split() for i in range(N)], dtype =int)
C = numpy.dot(A,B)
print(C)




 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


### Inner and Outer



In [23]:
import numpy
a = numpy.array(input().split() , int)
b = numpy.array(input().split() , int)
print(numpy.inner(a, b))
print(numpy.outer(a, b))




 0 1
 2 3


3
[[0 0]
 [2 3]]


### Polynomials



In [20]:
import numpy

m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))



 1.1 2 3
 0


3.0


### Linear Algebra



In [24]:
import numpy

numpy.set_printoptions(legacy='1.13')

N = int(input())

A = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(A))



 2
 1.1 1.1
 1.1 1.1


0.0


# Problem 2

### Birthday Cake Candles



In [ ]:
#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles):
    candles.sort()

    result = candles.count(candles[len(candles)-1])
    return result


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(raw_input().strip())

    candles = map(int, raw_input().rstrip().split())

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()


### Insertion Sort - Part 1



In [ ]:
#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    probe = arr[-1]
    
    for ind in range(len(arr)-2, -1, -1):
        if arr[ind] > probe:
            arr[ind+1] = arr[ind]
            print(" ".join(map(str, arr)))
        else:
            arr[ind+1] = probe
            print(" ".join(map(str, arr)))
            break
    if arr[0] > probe:
        arr[0] = probe
        print(" ".join(map(str, arr)))

if __name__ == '__main__':
    n = int(raw_input().strip())

    arr = map(int, raw_input().rstrip().split())

    insertionSort1(n, arr)


### Recursive Digit Sum

In [26]:
def superDigit(n, k):
    return 1 + (k * sum(int(x) for x in n) - 1) % 9